# Generated by Django 4.1.7 on 2023-03-10 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 10, 20, 15, 45, 495937)),
        ),
    ]
