# Generated by Django 4.1.7 on 2023-03-10 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_posts_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 10, 20, 25, 25, 686048)),
        ),
    ]
