# Generated by Django 4.1.7 on 2023-03-21 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_like_time_alter_posts_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 21, 14, 5, 35, 606604)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 14, 5, 35, 606223)),
        ),
    ]
